### ISSUE TITLE
'null' is not defined

### ISSUE THREAD

**Issue by Nihal-Tiwari** [Spidy-PS/Steganography-Tools#3]
python3 test.ipynb       #this is the command which I ran  
Traceback (most recent call last):
  File "/root/test/test.ipynb", line 807, in <module>
    "execution_count": null,
NameError: name 'null' is not defined

**Comment by Priyansh-15** [comment]
Hii @Nihal-Tiwari 
Can you please attach code and Snips regarding the same .

**Comment by Nihal-Tiwari** [comment]
is it supposed to be run on Google Collab I just tried the code on google collab and it's working but it's not working when I am running in VS code or linux terminal

**Comment by Priyansh-15** [comment]
@Nihal-Tiwari 
The Project can work on all platform with the required Import files .

**Comment by Nihal-Tiwari** [comment]
> @Nihal-Tiwari The Project can work on all platform with the required Import files .

Hey thanks I am able to run it :)
