### ISSUE TITLE
Encoded data video has no sound

### ISSUE THREAD

**Issue by M-Waleed** [Spidy-PS/Steganography-Tools#4]
I have tried encoding text into two videos. They have sound but sound disappears after encoding.

Does this steganography really disappear the video sound or it is an error? Thanks

**Comment by Priyansh-15** [comment]
Video steganography ensures sound as well as images frame and we just hide our text in image of a particular frame so it will not affect the sound .
On my system there is no such error , @M-Waleed  Please try using video file of ".mp4 type" .  According to me it's just a system type error for you  .

Hope this helped !!
Thanks :)

**Comment by miszuoer** [comment]
The code only output video stream into the new file, so it does not have any audio stream at all. You can play your encoded file in a vlc player.
